server:
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mysql://database-2.cbtfuwm9aisc.ap-northeast-2.rds.amazonaws.com:3306/hackaton?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: chatgpt!!
  driver-class-name: com.mysql.cj.jdbc.Driver
  mustache:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    hibernate:
      ddl-auto:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


hackaton:
  openai-api-key: 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